{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: postgresql-policy
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: postgresql
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ .Values.inventoryService.name }}
        - podSelector:
            matchLabels:
              app: {{ .Values.userService.name }}
        - podSelector:
            matchLabels:
              app: {{ .Values.authService.name }}
      ports:
        - protocol: TCP
          port: 5432
{{- end }}